
image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - install
  - test

install:
  stage: install
  script:
    - git config --global http.sslVerify "false"
    - npm config set strict-ssl false
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour      

test:
  stage: test
  script:
    - node install.js



